### ISSUE TITLE
QR code is unreadable

### ISSUE THREAD

**Issue by mijorus** [lucianomurr/angular-estrai.me#43]
I'm trying with my defaut camera app (nothing phone 1) as well as a couple of 3rd party one you can find on the playstore, none of them seems to be able to read the code quickly or at all.

I guess the image in the center is messing things up a bit, as the following code I made with a 3rd party app works just fine.

My suggestion would be simply to remove it

![image](https://user-images.githubusercontent.com/39067225/229052431-56603d90-e785-4a8c-97cb-8265854a57c6.png)

**Comment by lucianomurr** [comment]
Sometimes I'm facing the same issue, so yes, removing the image in the center could be an option to avoid this strange behavior!

**Comment by mijorus** [comment]
https://github.com/lucianomurr/angular-estrai.me/pull/44
